//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DataTableExpression.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DataTableExpressionParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IDataTableExpressionListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DataTableExpressionParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] DataTableExpressionParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DataTableExpressionParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] DataTableExpressionParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DataTableExpressionParser.orExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExpression([NotNull] DataTableExpressionParser.OrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DataTableExpressionParser.orExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExpression([NotNull] DataTableExpressionParser.OrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DataTableExpressionParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpression([NotNull] DataTableExpressionParser.AndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DataTableExpressionParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpression([NotNull] DataTableExpressionParser.AndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DataTableExpressionParser.notExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExpression([NotNull] DataTableExpressionParser.NotExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DataTableExpressionParser.notExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExpression([NotNull] DataTableExpressionParser.NotExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DataTableExpressionParser.comparisonExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparisonExpression([NotNull] DataTableExpressionParser.ComparisonExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DataTableExpressionParser.comparisonExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparisonExpression([NotNull] DataTableExpressionParser.ComparisonExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>InList</c>
	/// labeled alternative in <see cref="DataTableExpressionParser.inExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInList([NotNull] DataTableExpressionParser.InListContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>InList</c>
	/// labeled alternative in <see cref="DataTableExpressionParser.inExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInList([NotNull] DataTableExpressionParser.InListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DataTableExpressionParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] DataTableExpressionParser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DataTableExpressionParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] DataTableExpressionParser.AdditiveExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DataTableExpressionParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] DataTableExpressionParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DataTableExpressionParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] DataTableExpressionParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DataTableExpressionParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] DataTableExpressionParser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DataTableExpressionParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] DataTableExpressionParser.UnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DataTableExpressionParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpression([NotNull] DataTableExpressionParser.PrimaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DataTableExpressionParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpression([NotNull] DataTableExpressionParser.PrimaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DataTableExpressionParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] DataTableExpressionParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DataTableExpressionParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] DataTableExpressionParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DataTableExpressionParser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionName([NotNull] DataTableExpressionParser.FunctionNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DataTableExpressionParser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionName([NotNull] DataTableExpressionParser.FunctionNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DataTableExpressionParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentList([NotNull] DataTableExpressionParser.ArgumentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DataTableExpressionParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentList([NotNull] DataTableExpressionParser.ArgumentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DataTableExpressionParser.columnReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumnReference([NotNull] DataTableExpressionParser.ColumnReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DataTableExpressionParser.columnReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumnReference([NotNull] DataTableExpressionParser.ColumnReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DataTableExpressionParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] DataTableExpressionParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DataTableExpressionParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] DataTableExpressionParser.LiteralContext context);
}
