//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DataTableExpression.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="DataTableExpressionParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IDataTableExpressionVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="DataTableExpressionParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] DataTableExpressionParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DataTableExpressionParser.orExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExpression([NotNull] DataTableExpressionParser.OrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DataTableExpressionParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpression([NotNull] DataTableExpressionParser.AndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DataTableExpressionParser.notExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotExpression([NotNull] DataTableExpressionParser.NotExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DataTableExpressionParser.comparisonExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisonExpression([NotNull] DataTableExpressionParser.ComparisonExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DataTableExpressionParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpression([NotNull] DataTableExpressionParser.AdditiveExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DataTableExpressionParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpression([NotNull] DataTableExpressionParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DataTableExpressionParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] DataTableExpressionParser.UnaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DataTableExpressionParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpression([NotNull] DataTableExpressionParser.PrimaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DataTableExpressionParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] DataTableExpressionParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DataTableExpressionParser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionName([NotNull] DataTableExpressionParser.FunctionNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DataTableExpressionParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentList([NotNull] DataTableExpressionParser.ArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DataTableExpressionParser.columnReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumnReference([NotNull] DataTableExpressionParser.ColumnReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DataTableExpressionParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] DataTableExpressionParser.LiteralContext context);

	Result VisitInList(DataTableExpressionParser.InListContext context);
}
